atomic transaction for creating new user
labd/django-cognito-jwt pull request #1
Opened 2018-03-05 10:48 UTC by mikedebock

Atomic transaction for creating new user, when firing multiple requests at same time.

2018-03-05 12:23 UTC, mvantellingen requested changes

2018-03-05 12:23 UTC, mvantellingen commented on src/django_cognito_jwt/backend.py
> +    @transaction.atomic
We should only wrap line 54 in the atomic clause

2018-03-05 12:23 UTC, mvantellingen commented on src/django_cognito_jwt/backend.py
> +from django.db import transaction
ordering ;p

2018-03-05 12:26 UTC, mvantellingen commented
BTW; using a transaction can still result in an error when concurrent requests are done. This should be handled with a try/except clause (select user, insert if no user, if insert fails due to duplicate, retrieve user)

2018-03-07 12:15 UTC, mikedebock commented
This pr is unnecessary, fixed in get_or_create_for_cognito method.

2018-03-07 12:15 UTC, closed without merging